-- ============================================================
-- Doctor AI CRM Custom Schema
-- Adds: products, contact_products, conversations tables
-- Modifies: contacts (lead_source, contact_type)
--           deals (product_id, lead_source, won_lost_reason)
-- ============================================================

-- New table: products
create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "category" text not null check (category in ('workshop', 'academy', 'certification', 'corporate')),
    "price" numeric(10, 2) not null default 0,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

grant delete on table "public"."products" to "authenticated";
grant insert on table "public"."products" to "authenticated";
grant select on table "public"."products" to "authenticated";
grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";
grant insert on table "public"."products" to "service_role";
grant references on table "public"."products" to "service_role";
grant select on table "public"."products" to "service_role";
grant trigger on table "public"."products" to "service_role";
grant truncate on table "public"."products" to "service_role";
grant update on table "public"."products" to "service_role";

create policy "Enable read access for authenticated users" on "public"."products" as permissive for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."products" as permissive for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."products" as permissive for update to authenticated using (true) with check (true);
create policy "Products Delete Policy" on "public"."products" as permissive for delete to authenticated using (true);


-- New table: contact_products (join)
create table "public"."contact_products" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint not null,
    "product_id" bigint not null,
    "type" text not null check (type in ('purchased', 'interested')),
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."contact_products" enable row level security;

CREATE UNIQUE INDEX contact_products_pkey ON public.contact_products USING btree (id);

alter table "public"."contact_products" add constraint "contact_products_pkey" PRIMARY KEY using index "contact_products_pkey";

alter table "public"."contact_products" add constraint "contact_products_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."contact_products" validate constraint "contact_products_contact_id_fkey";

alter table "public"."contact_products" add constraint "contact_products_product_id_fkey"
    FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."contact_products" validate constraint "contact_products_product_id_fkey";

grant delete on table "public"."contact_products" to "authenticated";
grant insert on table "public"."contact_products" to "authenticated";
grant select on table "public"."contact_products" to "authenticated";
grant update on table "public"."contact_products" to "authenticated";

grant delete on table "public"."contact_products" to "service_role";
grant insert on table "public"."contact_products" to "service_role";
grant references on table "public"."contact_products" to "service_role";
grant select on table "public"."contact_products" to "service_role";
grant trigger on table "public"."contact_products" to "service_role";
grant truncate on table "public"."contact_products" to "service_role";
grant update on table "public"."contact_products" to "service_role";

create policy "Enable read access for authenticated users" on "public"."contact_products" as permissive for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."contact_products" as permissive for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."contact_products" as permissive for update to authenticated using (true) with check (true);
create policy "Contact Products Delete Policy" on "public"."contact_products" as permissive for delete to authenticated using (true);


-- New table: conversations
create table "public"."conversations" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint not null,
    "date" date not null default current_date,
    "channel" text not null check (channel in ('phone', 'zoom', 'dm', 'email', 'other')),
    "summary" text,
    "outcome" text check (outcome in ('follow_up', 'proposal_sent', 'closed_won', 'no_action')),
    "next_step" text,
    "task_id" bigint,
    "sales_id" bigint,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."conversations" enable row level security;

CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (id);

alter table "public"."conversations" add constraint "conversations_pkey" PRIMARY KEY using index "conversations_pkey";

alter table "public"."conversations" add constraint "conversations_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."conversations" validate constraint "conversations_contact_id_fkey";

alter table "public"."conversations" add constraint "conversations_task_id_fkey"
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."conversations" validate constraint "conversations_task_id_fkey";

alter table "public"."conversations" add constraint "conversations_sales_id_fkey"
    FOREIGN KEY (sales_id) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."conversations" validate constraint "conversations_sales_id_fkey";

grant delete on table "public"."conversations" to "authenticated";
grant insert on table "public"."conversations" to "authenticated";
grant select on table "public"."conversations" to "authenticated";
grant update on table "public"."conversations" to "authenticated";

grant delete on table "public"."conversations" to "service_role";
grant insert on table "public"."conversations" to "service_role";
grant references on table "public"."conversations" to "service_role";
grant select on table "public"."conversations" to "service_role";
grant trigger on table "public"."conversations" to "service_role";
grant truncate on table "public"."conversations" to "service_role";
grant update on table "public"."conversations" to "service_role";

create policy "Enable read access for authenticated users" on "public"."conversations" as permissive for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."conversations" as permissive for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."conversations" as permissive for update to authenticated using (true) with check (true);
create policy "Conversations Delete Policy" on "public"."conversations" as permissive for delete to authenticated using (true);


-- Modify contacts: add lead_source and contact_type
alter table "public"."contacts"
    add column "lead_source" text check (lead_source in ('tiktok', 'workshop', 'youtube', 'referral', 'linkedin', 'cold_outreach', 'other')),
    add column "contact_type" text check (contact_type in ('lead', 'student', 'client', 'corporate', 'alumni'));


-- Modify deals: add product_id, lead_source, won_lost_reason
alter table "public"."deals"
    add column "product_id" bigint,
    add column "lead_source" text check (lead_source in ('tiktok', 'workshop', 'youtube', 'referral', 'linkedin', 'cold_outreach', 'other')),
    add column "won_lost_reason" text;

alter table "public"."deals" add constraint "deals_product_id_fkey"
    FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."deals" validate constraint "deals_product_id_fkey";
