-- ============================================================
-- Payments and Subscriptions tables for Stripe integration
-- ============================================================

-- New table: payments
create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint,
    "stripe_payment_id" text not null,
    "stripe_customer_id" text,
    "stripe_invoice_id" text,
    "stripe_subscription_id" text,
    "amount" numeric(10, 2) not null,
    "currency" text not null default 'usd',
    "status" text not null check (status in ('succeeded', 'pending', 'failed', 'refunded')),
    "type" text not null check (type in ('one_time', 'subscription', 'refund')),
    "description" text,
    "stripe_account" text not null check (stripe_account in ('community', 'consulting')),
    "stripe_customer_email" text,
    "stripe_event_id" text,
    "metadata" jsonb,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."payments" enable row level security;

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);
CREATE UNIQUE INDEX payments_stripe_payment_id_key ON public.payments USING btree (stripe_payment_id);
CREATE INDEX payments_contact_id_idx ON public.payments USING btree (contact_id);
CREATE INDEX payments_stripe_customer_id_idx ON public.payments USING btree (stripe_customer_id);
CREATE INDEX payments_stripe_event_id_idx ON public.payments USING btree (stripe_event_id);

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";
alter table "public"."payments" add constraint "payments_stripe_payment_id_key" UNIQUE using index "payments_stripe_payment_id_key";

alter table "public"."payments" add constraint "payments_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."payments" validate constraint "payments_contact_id_fkey";

grant delete on table "public"."payments" to "authenticated";
grant insert on table "public"."payments" to "authenticated";
grant select on table "public"."payments" to "authenticated";
grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";
grant insert on table "public"."payments" to "service_role";
grant references on table "public"."payments" to "service_role";
grant select on table "public"."payments" to "service_role";
grant trigger on table "public"."payments" to "service_role";
grant truncate on table "public"."payments" to "service_role";
grant update on table "public"."payments" to "service_role";

create policy "Enable read access for authenticated users" on "public"."payments" as permissive for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."payments" as permissive for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."payments" as permissive for update to authenticated using (true) with check (true);
create policy "Payments Delete Policy" on "public"."payments" as permissive for delete to authenticated using (true);


-- New table: subscriptions
create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint,
    "stripe_subscription_id" text not null,
    "stripe_customer_id" text,
    "status" text not null check (status in ('active', 'past_due', 'canceled', 'unpaid', 'trialing', 'incomplete', 'incomplete_expired', 'paused')),
    "stripe_price_id" text,
    "stripe_product_id" text,
    "current_period_start" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    "cancel_at" timestamp with time zone,
    "canceled_at" timestamp with time zone,
    "stripe_account" text not null check (stripe_account in ('community', 'consulting')),
    "stripe_customer_email" text,
    "metadata" jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."subscriptions" enable row level security;

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);
CREATE UNIQUE INDEX subscriptions_stripe_subscription_id_key ON public.subscriptions USING btree (stripe_subscription_id);
CREATE INDEX subscriptions_contact_id_idx ON public.subscriptions USING btree (contact_id);
CREATE INDEX subscriptions_stripe_customer_id_idx ON public.subscriptions USING btree (stripe_customer_id);

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";
alter table "public"."subscriptions" add constraint "subscriptions_stripe_subscription_id_key" UNIQUE using index "subscriptions_stripe_subscription_id_key";

alter table "public"."subscriptions" add constraint "subscriptions_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."subscriptions" validate constraint "subscriptions_contact_id_fkey";

grant delete on table "public"."subscriptions" to "authenticated";
grant insert on table "public"."subscriptions" to "authenticated";
grant select on table "public"."subscriptions" to "authenticated";
grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";
grant insert on table "public"."subscriptions" to "service_role";
grant references on table "public"."subscriptions" to "service_role";
grant select on table "public"."subscriptions" to "service_role";
grant trigger on table "public"."subscriptions" to "service_role";
grant truncate on table "public"."subscriptions" to "service_role";
grant update on table "public"."subscriptions" to "service_role";

create policy "Enable read access for authenticated users" on "public"."subscriptions" as permissive for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."subscriptions" as permissive for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."subscriptions" as permissive for update to authenticated using (true) with check (true);
create policy "Subscriptions Delete Policy" on "public"."subscriptions" as permissive for delete to authenticated using (true);
