-- ============================================================
-- Payment & Subscription Tracking
-- Adds: payments, subscriptions tables
-- Views: revenue_summary, mrr_summary
-- ============================================================

-- Payments table
CREATE TABLE IF NOT EXISTS payments (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contact_id bigint REFERENCES contacts(id) ON DELETE SET NULL,
    amount numeric(10,2) NOT NULL,
    currency text DEFAULT 'usd',
    payment_type text NOT NULL CHECK (payment_type IN ('one_time', 'subscription', 'refund')),
    status text NOT NULL DEFAULT 'succeeded' CHECK (status IN ('succeeded', 'pending', 'failed', 'refunded', 'canceled')),
    description text,
    stripe_payment_id text,
    stripe_subscription_id text,
    stripe_account text CHECK (stripe_account IN ('community', 'consulting')),
    product_id bigint REFERENCES products(id) ON DELETE SET NULL,
    payment_date timestamp with time zone DEFAULT now(),
    sales_id bigint REFERENCES sales(id),
    created_at timestamp with time zone DEFAULT now()
);

CREATE INDEX idx_payments_contact ON payments(contact_id);
CREATE INDEX idx_payments_date ON payments(payment_date);
CREATE INDEX idx_payments_stripe_id ON payments(stripe_payment_id);

-- Subscriptions table for recurring revenue tracking
CREATE TABLE IF NOT EXISTS subscriptions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contact_id bigint REFERENCES contacts(id) ON DELETE SET NULL,
    stripe_subscription_id text,
    stripe_account text CHECK (stripe_account IN ('community', 'consulting')),
    product_id bigint REFERENCES products(id) ON DELETE SET NULL,
    plan_name text,
    amount numeric(10,2) NOT NULL,
    currency text DEFAULT 'usd',
    interval text NOT NULL CHECK (interval IN ('monthly', 'yearly')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'trial', 'past_due', 'canceled', 'ended')),
    start_date timestamp with time zone,
    current_period_end timestamp with time zone,
    canceled_at timestamp with time zone,
    sales_id bigint REFERENCES sales(id),
    created_at timestamp with time zone DEFAULT now()
);

CREATE INDEX idx_subscriptions_contact ON subscriptions(contact_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);
CREATE INDEX idx_subscriptions_stripe_id ON subscriptions(stripe_subscription_id);

-- RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage payments" ON payments FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can manage subscriptions" ON subscriptions FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Grants for authenticated role
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE payments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE subscriptions TO authenticated;

-- Grants for service_role
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE payments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE subscriptions TO service_role;

-- Auto-set sales_id triggers (reuses set_sales_id_default from task_default_sales migration)
CREATE TRIGGER on_payment_created
    BEFORE INSERT ON payments
    FOR EACH ROW
    EXECUTE FUNCTION set_sales_id_default();

CREATE TRIGGER on_subscription_created
    BEFORE INSERT ON subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION set_sales_id_default();

-- Revenue summary view
CREATE OR REPLACE VIEW revenue_summary AS
SELECT
    date_trunc('month', payment_date) as month,
    SUM(CASE WHEN payment_type = 'one_time' THEN amount ELSE 0 END) as one_time_revenue,
    SUM(CASE WHEN payment_type = 'subscription' THEN amount ELSE 0 END) as subscription_revenue,
    SUM(CASE WHEN payment_type = 'refund' THEN amount ELSE 0 END) as refunds,
    SUM(amount) as total_revenue,
    COUNT(DISTINCT contact_id) as unique_customers
FROM payments
WHERE status = 'succeeded'
GROUP BY date_trunc('month', payment_date)
ORDER BY month DESC;

-- MRR view
CREATE OR REPLACE VIEW mrr_summary AS
SELECT
    COUNT(*) as active_subscriptions,
    SUM(CASE WHEN interval = 'monthly' THEN amount ELSE amount / 12 END) as mrr,
    SUM(CASE WHEN interval = 'monthly' THEN amount * 12 ELSE amount END) as arr,
    COUNT(CASE WHEN status = 'trial' THEN 1 END) as trial_count,
    COUNT(CASE WHEN status = 'active' THEN 1 END) as active_count
FROM subscriptions
WHERE status IN ('active', 'trial');
