-- ============================================================
-- Funnel Stage Tracking
-- Adds: funnel_stages lookup table, contact_stage_history table
-- Modifies: contacts (funnel_stage, funnel_stage_changed_at)
-- Updates: contacts_summary view
-- ============================================================

-- Funnel stages lookup table
CREATE TABLE IF NOT EXISTS funnel_stages (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    display_name text NOT NULL,
    sort_order smallint NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

-- Seed the funnel stages
INSERT INTO funnel_stages (name, display_name, sort_order) VALUES
    ('lead', 'Lead', 0),
    ('workshop_attendee', 'Workshop Attendee', 10),
    ('community_member', 'Community Member', 20),
    ('ai_consultant', 'AI Consultant', 30),
    ('coaching_client', 'Coaching Client', 40);

-- Stage history - tracks every transition with timestamp
CREATE TABLE IF NOT EXISTS contact_stage_history (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contact_id bigint NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    from_stage text,
    to_stage text NOT NULL,
    changed_at timestamp with time zone DEFAULT now(),
    changed_by uuid REFERENCES auth.users(id),
    notes text,
    sales_id bigint,
    created_at timestamp with time zone DEFAULT now()
);

CREATE INDEX idx_stage_history_contact ON contact_stage_history(contact_id);
CREATE INDEX idx_stage_history_changed_at ON contact_stage_history(changed_at);

-- Add funnel_stage column to contacts if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contacts' AND column_name = 'funnel_stage') THEN
        ALTER TABLE contacts ADD COLUMN funnel_stage text DEFAULT 'lead';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contacts' AND column_name = 'funnel_stage_changed_at') THEN
        ALTER TABLE contacts ADD COLUMN funnel_stage_changed_at timestamp with time zone DEFAULT now();
    END IF;
END $$;

-- RLS policies for funnel_stages
ALTER TABLE funnel_stages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read funnel_stages" ON funnel_stages FOR SELECT TO authenticated USING (true);

-- Grants for funnel_stages
grant select on table "public"."funnel_stages" to "authenticated";
grant select on table "public"."funnel_stages" to "service_role";
grant insert on table "public"."funnel_stages" to "service_role";
grant update on table "public"."funnel_stages" to "service_role";
grant delete on table "public"."funnel_stages" to "service_role";

-- RLS policies for contact_stage_history
ALTER TABLE contact_stage_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read contact_stage_history" ON contact_stage_history FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert contact_stage_history" ON contact_stage_history FOR INSERT TO authenticated WITH CHECK (true);

-- Grants for contact_stage_history
grant select on table "public"."contact_stage_history" to "authenticated";
grant insert on table "public"."contact_stage_history" to "authenticated";

grant select on table "public"."contact_stage_history" to "service_role";
grant insert on table "public"."contact_stage_history" to "service_role";
grant update on table "public"."contact_stage_history" to "service_role";
grant delete on table "public"."contact_stage_history" to "service_role";
grant references on table "public"."contact_stage_history" to "service_role";
grant trigger on table "public"."contact_stage_history" to "service_role";
grant truncate on table "public"."contact_stage_history" to "service_role";

-- Auto-set sales_id trigger for contact_stage_history (follow existing pattern)
CREATE TRIGGER set_contact_stage_history_sales_id_trigger
    BEFORE INSERT ON contact_stage_history
    FOR EACH ROW
    EXECUTE FUNCTION set_sales_id_default();

-- Trigger to auto-log stage changes when funnel_stage is updated on contacts
CREATE OR REPLACE FUNCTION handle_contact_stage_change()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.funnel_stage IS DISTINCT FROM NEW.funnel_stage THEN
        INSERT INTO contact_stage_history (contact_id, from_stage, to_stage, changed_by)
        VALUES (NEW.id, OLD.funnel_stage, NEW.funnel_stage, auth.uid());
        NEW.funnel_stage_changed_at = now();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_contact_funnel_stage_change
    BEFORE UPDATE ON contacts
    FOR EACH ROW
    EXECUTE FUNCTION handle_contact_stage_change();

-- Update contacts_summary view to include funnel_stage and funnel_stage_changed_at
drop view if exists contacts_summary;

create view contacts_summary
as
select
    co.*,
    jsonb_path_query_array(co.email_jsonb, '$[*].email')::text as email_fts,
    jsonb_path_query_array(co.phone_jsonb, '$[*].number')::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from
    contacts co
left join
    tasks t on co.id = t.contact_id
left join
    companies c on co.company_id = c.id
group by
    co.id, c.name;
